name: "Dev Release"

on:
  push:
    branches:
      - "development"

jobs:
  pre-release:
    name: "Create Dev-Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: "Create Release"
      run: |
         echo "done!"

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest" #${{ github.ref }}
          prerelease: true
          title: "Development Build"
          files: |
            target/*.jar
