name: "Dev Release"

on:
  push:
    branches:
      - "development"

jobs:
  dev-release:
    name: "Create Dev-Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'


    - name: "Get data"
      id: metadata
      run: |
        echo ::set-output name=VERSION::$(php -r 'echo explode("+", explode("-", yaml_parse_file(getcwd() . DIRECTORY_SEPARATOR . "src/main/resources/plugin.yml")["version"])[0])[0];')
        echo ::set-output name=FULL_VERSION::$(php -r 'echo yaml_parse_file(getcwd() . DIRECTORY_SEPARATOR .                      "src/main)/resources/plugin.yml")["version"];')
        echo ::set-output name=NAME::$(php -r 'echo yaml_parse_file(getcwd() . DIRECTORY_SEPARATOR .                              "src/main/resources/plugin.yml")["name"];')

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: "Create Development Release"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Development Release v${{ steps.metadata.outputs.VERSION }}"
          files: |
            target/*.jar
            target/*.zip
